### ISSUE TITLE
Question: What is the best way to test/classify the type?

### ISSUE THREAD

**Issue by mwalkerwells** [sanctuary-js/sanctuary-pair#6]
This is how'd I'd expect to do it, but `$.Pair` does not exist...
```js
S.is($.Pair ($.Any) ($.Any) )
```

**Comment by davidchambers** [comment]
You could use [`S.PairType`][1]. :)


[1]: https://sanctuary.js.org/#PairType

**Comment by mwalkerwells** [comment]
Oh, interesting... I was looking here: https://github.com/sanctuary-js/sanctuary-def/blob/master/index.js#L2617-L2673
